[options]
girs_dir = "../../gir-files"
library = "Nice"
version = "0.1"
target_path = "."
min_cfg_version = "0.1"
work_mode="sys"

external_libraries = [
  "Glib",
]

[external_libraries] 
gio="Gio" 
gobject="GObject"
