[options]
girs_dir = "../gir-files"
library = "Nice"
version = "0.1"
target_path = "."
min_cfg_version = "0.1"
work_mode = "normal"
concurrency = "send+sync"
generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = true

external_libraries = [
  "Glib",
  "GObject",
  "Gio",
]

generate = [
  "Nice.Agent",
  "Nice.ComponentType",
  "Nice.Compatibility",
  "Nice.AgentOption",
  "Nice.RelayType",
  "Nice.CandidateType",
  "Nice.CandidateTransport",
  "Nice.NominationMode",
  "Nice.ProxyType",
]

manual = [
  "GLib.MainContext",
  "GLib.Error",
  "Gio.AsyncReadyCallback",
  "Gio.Socket",
  "Gio.Cancellable",
  "Gio.IOStream"
]

[[object]]
name = "Nice.ComponentState"
status = "generate"
    [[object.member]]
    name = "last"
    ignore = true

